export const DocumentErrorCode = {
  BLOCK_ALREADY_EXISTS: "DOCUMENT:BLOCK_ALREADY_EXISTS",
  INVALID_PARENT_BLOCK: "DOCUMENT:INVALID_PARENT_BLOCK",
  PARENT_BLOCK_CANNOT_HAVE_CHILDREN: "DOCUMENT:PARENT_BLOCK_CANNOT_HAVE_CHILDREN",
  BLOCK_CANNOT_HAVE_CHILDREN: "DOCUMENT:BLOCK_CANNOT_HAVE_CHILDREN",
  BLOCK_CANNOT_CONTAIN_ITSELF: "DOCUMENT:BLOCK_CANNOT_CONTAIN_ITSELF",
  INVALID_DOCUMENT_JSON: "DOCUMENT:INVALID_DOCUMENT_JSON",
  INVALID_DOCUMENT_STRUCTURE: "DOCUMENT:INVALID_DOCUMENT_STRUCTURE",
  INVALID_DOCUMENT_ROOT_ID: "DOCUMENT:INVALID_DOCUMENT_ROOT_ID",
  INVALID_BLOCK_PARENT_ID: "DOCUMENT:INVALID_BLOCK_PARENT_ID",
  DUPLICATE_OR_CIRCULAR_BLOCK: "DOCUMENT:DUPLICATE_OR_CIRCULAR_BLOCK",
  PARENT_BLOCK_NOT_FOUND: "DOCUMENT:PARENT_BLOCK_NOT_FOUND",
  INVALID_BLOCK_TYPE: "DOCUMENT:INVALID_BLOCK_TYPE",
  BLOCK_IS_NOT_AN_OBJECT: "DOCUMENT:BLOCK_IS_NOT_AN_OBJECT",
  INVALID_BLOCK_ID: "DOCUMENT:INVALID_BLOCK_ID",
  INVALID_BLOCK_VARIANT: "DOCUMENT:INVALID_BLOCK_VARIANT",
  CANNOT_INSERT_BEFORE_ROOT: "DOCUMENT:CANNOT_INSERT_BEFORE_ROOT",
  CANNOT_INSERT_AFTER_ROOT: "DOCUMENT:CANNOT_INSERT_AFTER_ROOT",
  TARGET_BLOCK_NOT_FOUND: "DOCUMENT:TARGET_BLOCK_NOT_FOUND",
  PARENT_OF_TARGET_NOT_FOUND: "DOCUMENT:PARENT_OF_TARGET_NOT_FOUND",
  PARENT_OF_TARGET_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:PARENT_OF_TARGET_CANNOT_HAVE_CHILDREN",
  TARGET_NOT_IN_PARENT_CHILDREN: "DOCUMENT:TARGET_NOT_IN_PARENT_CHILDREN",
  CANNOT_REMOVE_ROOT: "DOCUMENT:CANNOT_REMOVE_ROOT",
  BLOCK_TO_REMOVE_NOT_FOUND: "DOCUMENT:BLOCK_TO_REMOVE_NOT_FOUND",
  BLOCK_TO_REMOVE_HAS_NO_PARENT: "DOCUMENT:BLOCK_TO_REMOVE_HAS_NO_PARENT",
  PARENT_OF_BLOCK_HAS_NO_CHILDREN: "DOCUMENT:PARENT_OF_BLOCK_HAS_NO_CHILDREN",
  CANNOT_MOVE_BLOCK_TO_ITSELF: "DOCUMENT:CANNOT_MOVE_BLOCK_TO_ITSELF",
  CANNOT_MOVE_ROOT: "DOCUMENT:CANNOT_MOVE_ROOT",
  CAN_ONLY_APPEND_TO_ROOT: "DOCUMENT:CAN_ONLY_APPEND_TO_ROOT",
  BLOCK_TO_MOVE_NOT_FOUND: "DOCUMENT:BLOCK_TO_MOVE_NOT_FOUND",
  TARGET_BLOCK_CANNOT_HAVE_CHILDREN: "DOCUMENT:TARGET_BLOCK_CANNOT_HAVE_CHILDREN",
  CANNOT_MOVE_BLOCK_TO_DESCENDANT: "DOCUMENT:CANNOT_MOVE_BLOCK_TO_DESCENDANT",
  INVALID_MOVE_STRATEGY: "DOCUMENT:INVALID_MOVE_STRATEGY",
  CANNOT_UPDATE_ROOT: "DOCUMENT:CANNOT_UPDATE_ROOT",
  BLOCK_TO_UPDATE_NOT_FOUND: "DOCUMENT:BLOCK_TO_UPDATE_NOT_FOUND",
  BLOCK_TO_UPDATE_HAS_NO_PARENT: "DOCUMENT:BLOCK_TO_UPDATE_HAS_NO_PARENT",
  UPDATE_BLOCK_ID_ALREADY_IN_USE: "DOCUMENT:UPDATE_BLOCK_ID_ALREADY_IN_USE",
  CANNOT_PRESERVE_CHILDREN_NEW_BLOCK_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:CANNOT_PRESERVE_CHILDREN_NEW_BLOCK_CANNOT_HAVE_CHILDREN",
  CANNOT_PRESERVE_CHILDREN_OLD_BLOCK_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:CANNOT_PRESERVE_CHILDREN_OLD_BLOCK_CANNOT_HAVE_CHILDREN",
  CANNOT_REPLACE_CHILDREN_BOTH_BLOCKS_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:CANNOT_REPLACE_CHILDREN_BOTH_BLOCKS_CANNOT_HAVE_CHILDREN",
  CANNOT_REPLACE_CHILDREN_NEW_BLOCK_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:CANNOT_REPLACE_CHILDREN_NEW_BLOCK_CANNOT_HAVE_CHILDREN",
  CANNOT_REPLACE_CHILDREN_OLD_BLOCK_CANNOT_HAVE_CHILDREN:
    "DOCUMENT:CANNOT_REPLACE_CHILDREN_OLD_BLOCK_CANNOT_HAVE_CHILDREN",
  CANNOT_REPLACE_CHILDREN_NO_CHILDREN_PROVIDED:
    "DOCUMENT:CANNOT_REPLACE_CHILDREN_NO_CHILDREN_PROVIDED",
  UPDATE_BLOCK_CHILD_ID_ALREADY_EXISTS:
    "DOCUMENT:UPDATE_BLOCK_CHILD_ID_ALREADY_EXISTS",
  UPDATE_BLOCK_CHILD_ID_EQUALS_SUBTREE_ROOT:
    "DOCUMENT:UPDATE_BLOCK_CHILD_ID_EQUALS_SUBTREE_ROOT",
} as const;
