name: "Setup CI Environment"
description: "Sets up Node.js, Corepack (pnpm), and caching for CI jobs"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Ensure pnpm store exists
      run: mkdir -p ~/.pnpm-store
      shell: bash

    - name: Cache pnpm store
      uses: actions/cache@v4
      id: cache
      with:
        # TODO: Make it work with ~/.pnpm-store.
        path: node_modules
        key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Build the packages
      run: pnpm -r build
      shell: bash
